version: '3.8'

services:
  web:
    env_file: .env
    image: php:8.1-apache
    container_name: php_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      # - ./src:/var/www/html/src
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    env_file: .env
    image: mysql:8
    container_name: mysql_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: temperature_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d  # 初期化用スクリプトをマウント

volumes:
  db_data:
